
repo: "https://github.com/amitkaps/full-stack-data-science.git"

system_packages:
  - supervisor

services:
  - name: square
    command: /usr/local/anaconda3/bin/firefly -b 0.0.0.0:7000 sq.square
    directory: /root/full-stack-data-science/firefly-examples