
repo: "https://github.com/amitkaps/full-stack-data-science.git"

system_packages:
  - supervisor

services:
  - name: square
    command: /usr/local/anaconda3/bin/firefly -b 0.0.0.0:7000 sq.square
    directory: /root/full-stack-data-science/firefly-examples

  - name: credit-grade
    command: /usr/local/anaconda3/bin/firefly -b 0.0.0.0:7001 credit_grade.find_credit_grade
    directory: /root/full-stack-data-science/credit-risk

  - name: credit-risk-service
    command: /usr/local/anaconda3/bin/firefly -b 0.0.0.0:7002 credit_risk_service.predict
    directory: /root/full-stack-data-science/credit-risk    